apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./repo/apps/dev
  prune: true
  postBuild:
    substitute:
      cluster_tz: "America/Santo_Domingo"
      domain: "aanetworks.org"
      domain_ts: "wolf-coho.ts.net"
