kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: adguard-home-config
  labels:
    app.kubernetes.io/name: adguard-home
    app.kubernetes.io/instance: adguard-home
  annotations:
    volume.beta.kubernetes.io/storage-class: "harvester"
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
